In [36]:
from tlspt.datamodules.components.numpy_dataset import NumpyDataset
from tlspt.datamodules.components.base_site import BaseSiteDataset
from tlspt.datamodules.components.octree_dataset import OctreeDataset
from tlspt.datamodules.components.merged_dataset import MergedOctreeDataset
from tlspt.transforms import TLSSampler, UniformDownsample
from tlspt.datamodules.single_datamodule import SingleDataModule

from torch.utils.data import DataLoader


from matplotlib import pyplot as plt

import numpy as np

In [2]:
base_dataset = BaseSiteDataset(split_file='../data/plot_octrees/allen-spain/octrees/allen-spain-plot_splits-tr0.7-val0.15-te0.15_seed0.csv', 
                               split='train', 
                               dataset='test', 
                               voxel_format='npy')

2024-11-20 16:20:29.437 | INFO     | tlspt.datamodules.components.base_site:__init__:49 - test: reading splits from ../data/plot_octrees/allen-spain/octrees/allen-spain-plot_splits-tr0.7-val0.15-te0.15_seed0.csv
2024-11-20 16:20:29.472 | INFO     | tlspt.datamodules.components.base_site:__init__:56 - test: looking for 14 folders in ../data/plot_octrees/allen-spain/octrees/
2024-11-20 16:20:29.490 | INFO     | tlspt.datamodules.components.base_site:__init__:64 - test: found 14 plots for 'train' out of 14 plots defined in split file


In [3]:
site_dataset = OctreeDataset(split_file='../data/plot_octrees/allen-spain/octrees/allen-spain-plot_splits-tr0.7-val0.15-te0.15_seed0.csv',
                                 split='train',
                                 feature_names=['red', 'green', 'blue'],
                                 features_to_normalize=['red', 'green', 'blue'],
                                 scale=1.5,
                                 transform=UniformDownsample(num_points=1024, replace="resample_as_req"))

2024-11-20 16:20:29.643 | INFO     | tlspt.datamodules.components.base_site:__init__:49 - OctreeDataset(../data/plot_octrees/allen-spain/octrees/allen-spain-plot_splits-tr0.7-val0.15-te0.15_seed0.csv, train, 1.5): reading splits from ../data/plot_octrees/allen-spain/octrees/allen-spain-plot_splits-tr0.7-val0.15-te0.15_seed0.csv
2024-11-20 16:20:29.645 | INFO     | tlspt.datamodules.components.base_site:__init__:56 - OctreeDataset(../data/plot_octrees/allen-spain/octrees/allen-spain-plot_splits-tr0.7-val0.15-te0.15_seed0.csv, train, 1.5): looking for 14 folders in ../data/plot_octrees/allen-spain/octrees/
2024-11-20 16:20:29.646 | INFO     | tlspt.datamodules.components.base_site:__init__:64 - OctreeDataset(../data/plot_octrees/allen-spain/octrees/allen-spain-plot_splits-tr0.7-val0.15-te0.15_seed0.csv, train, 1.5): found 14 plots for 'train' out of 14 plots defined in split file
2024-11-20 16:20:30.023 | INFO     | tlspt.structures.file_octree:__init__:151 - Initializing octree from <cl

In [4]:
site_dataset.octrees[0]

In [5]:
len(site_dataset.nodes)

14

In [6]:
print(f"Number of nodes in DS plot 0: {len(site_dataset.nodes[0])}")

Number of nodes in DS plot 0: 1492


In [7]:
len(site_dataset.leaf_nodes[0])  #e.g. site_dataset.leaf_nodes[number of plot][number of parent node]
num_leaves_per_node = [len(x) for x in site_dataset.leaf_nodes[0]]
print(f"Number of leaves total in DS plot 0: {sum(num_leaves_per_node)}")

Number of leaves total in DS plot 0: 1492


In [8]:
len(site_dataset)

11318

In [9]:
site_dataset.load_item(0)

In [10]:
site_dataset.prepare_data(force_compute=False)

2024-11-20 16:20:31.998 | INFO     | tlspt.utils:prepare_data:95 - reading stats from ../data/plot_octrees/allen-spain/octrees/stats/stats_128a15cc4e5f0.pkl
2024-11-20 16:20:31.998 | INFO     | tlspt.utils:prepare_data:96 - for dataset OctreeDataset.{'features_to_normalize': ['red', 'green', 'blue']}.train.128a15cc4e5f0
2024-11-20 16:20:32.037 | INFO     | tlspt.utils:prepare_data:105 - mean: tensor([84.8191, 78.4194, 78.4236])
2024-11-20 16:20:32.038 | INFO     | tlspt.utils:prepare_data:106 - std: tensor([86.3282, 82.7727, 82.8428])
2024-11-20 16:20:32.038 | INFO     | tlspt.utils:prepare_data:110 - torch.float32
2024-11-20 16:20:32.039 | INFO     | tlspt.utils:prepare_data:114 - Dataset has 3 features named ['red', 'green', 'blue']. 
 Normalizing ['red', 'green', 'blue'] by mean+std. 
2024-11-20 16:20:32.039 | INFO     | tlspt.utils:prepare_data:117 - 3 channels will be zero centered and scaled to [-1,1].


In [ ]:
site_dataset[9]['features'].shape

torch.Size([1024, 3])

In [ ]:
site_dataset[9]['points'].shape

torch.Size([1024, 3])

In [ ]:
length = site_dataset[9]['length']
mat = np.array(site_dataset[9]['points'])  # Ensure 'mat' is a NumPy array

print(mat[0:5])  # Print first 5 points
print()
print(mat[length:length+5])  # Print points from 'length' to 'length + 5'

# Find indices of rows in 'mat' that are equal to the first row
indices = np.where(np.all(mat == mat[0], axis=1))[0]
print("Indices of rows equal to the first row:", indices)

print(len(mat))

[[-0.18321796  0.06674876  0.89226127]
 [ 0.13288184  0.03866037 -0.24192403]
 [-0.10442736  0.06023834  0.9733759 ]
 [ 0.11393438 -0.00452193 -0.22364217]
 [ 0.08081514  0.00418358 -0.23127441]]

[[-0.18321796  0.06674876  0.89226127]
 [ 0.13288184  0.03866037 -0.24192403]
 [-0.10442736  0.06023834  0.9733759 ]
 [ 0.11393438 -0.00452193 -0.22364217]
 [ 0.08081514  0.00418358 -0.23127441]]
Indices of rows equal to the first row: [  0 545]
1024


In [37]:
dataloader = DataLoader(site_dataset, batch_size=128, shuffle=True)

In [38]:
batch = next(iter(dataloader))

In [40]:
batch['length']

tensor([1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024,
        1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024,
         526, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024,
        1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024,
        1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024,  517, 1024, 1024, 1024,
        1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024,
        1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024,
        1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024,
         851,  764, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024,
        1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024,
        1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024])

In [34]:
merged_dataset = MergedOctreeDataset(
    split_files=['/home/matt/work/tlsPT/data/plot_octrees/allen-finland/octrees/allen-finland-plot_splits-tr0.7-val0.15-te0.15_seed0.csv',
                 '/home/matt/work/tlsPT/data/plot_octrees/allen-poland/octrees/allen-poland-plot_splits-tr0.7-val0.15-te0.15_seed0.csv',
                 '/home/matt/work/tlsPT/data/plot_octrees/allen-spain/octrees/allen-spain-plot_splits-tr0.7-val0.15-te0.15_seed0.csv'],
    split='train',
    scales=[1.5, 1.5, 1.5],
    feature_names=None,
    normalize=True,
    transform=UniformDownsample(num_points=1024, replace="resample_as_req")
)

2024-11-20 16:34:20.876 | INFO     | tlspt.datamodules.components.base_site:__init__:49 - OctreeDataset(/home/matt/work/tlsPT/data/plot_octrees/allen-finland/octrees/allen-finland-plot_splits-tr0.7-val0.15-te0.15_seed0.csv, train, 1.5): reading splits from /home/matt/work/tlsPT/data/plot_octrees/allen-finland/octrees/allen-finland-plot_splits-tr0.7-val0.15-te0.15_seed0.csv
2024-11-20 16:34:20.878 | INFO     | tlspt.datamodules.components.base_site:__init__:56 - OctreeDataset(/home/matt/work/tlsPT/data/plot_octrees/allen-finland/octrees/allen-finland-plot_splits-tr0.7-val0.15-te0.15_seed0.csv, train, 1.5): looking for 12 folders in /home/matt/work/tlsPT/data/plot_octrees/allen-finland/octrees/
2024-11-20 16:34:20.879 | INFO     | tlspt.datamodules.components.base_site:__init__:64 - OctreeDataset(/home/matt/work/tlsPT/data/plot_octrees/allen-finland/octrees/allen-finland-plot_splits-tr0.7-val0.15-te0.15_seed0.csv, train, 1.5): found 12 plots for 'train' out of 12 plots defined in split f